services:
  - type: web
    plan: free
    name: Filestorebot
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/rubankarthick/filestoreuhd
    branch: main
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: CHANNEL_ID 
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: START_MESSAGE
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
    autoDeploy: false 
